name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     run: 
    #      docker login -u farman82 -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        

    - name: Build and push Docker image
      run: |
        docker login -u farman82 -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        docker build -t farman82/devops-hello:latest .
        docker push farman82/devops-hello:latest

    # - name: Set up kubectl
    #   uses: azure/setup-kubectl@v3
    #   with:
    #     version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/devops-hello devops-hello=farman82/devops-hello:latest
